FROM mambaorg/micromamba:jammy

USER root
ENV DEBIAN_FRONTEND=noninteractive

# 安装核心系统依赖 (尤其是 MuJoCo 和视频渲染需要的库)
RUN apt-get -y update && \
    apt-get install -y --no-install-recommends build-essential git nano curl wget ffmpeg \
    libosmesa6-dev libgl1-mesa-glx libglfw3 libglew-dev mesa-utils patchelf xvfb && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# 将环境挂载到 mamba 用户下
USER $MAMBA_USER
COPY --chown=$MAMBA_USER:$MAMBA_USER environment.yaml /tmp/env.yaml

# 极速创建环境
RUN micromamba create -y -n tdmpc2 -f /tmp/env.yaml && \
    micromamba clean --all --yes

# 激活环境
ENV PATH="/opt/conda/envs/tdmpc2/bin:$PATH"