defaults:
    - override hydra/launcher: submitit_local

# ============================================================
# BeamNG
# ============================================================
beamng_host: localhost
beamng_port: 64256
beamng_home: /workspace/src/BeamNGtech
map: utah
vehicle_model: rockbouncer
vehicle_start_pos: 'auto'
vehicle_start_rot: [0.0, 0.0, 1.0, 0.0]
waypoint_file: "/workspace/src/BeamNGpy/data_collect/waypoints/route/route1.json"
npcs: []
steps_per_second: 10

# ============================================================
# agent training
# ============================================================
steps: 10_000_000 # 10M
episode_length: 500
seed_steps: ???
buffer_size: 30_000
batch_size: 256
horizon: 15
consistency_coef: 20
reward_coef: 0.1
value_coef: 0.1
termination_coef: 1

grad_clip_norm: 20
lr: 3e-4
enc_lr_scale: 0.3
tau: 0.01
discount_denom: 10
discount_min: 0.97
discount_max: 0.999
exp_name: default
data_dir: ???

# ============================================================
# agent evaluation
# ============================================================
eval_freq: 50000
eval_episodes: 10
checkpoint: ???

# ============================================================
# world model
# ============================================================
multitask: ???
obs: multimodal
obs_shape: 
  state: [15] 
  rgb: [9, 64, 64]

# ============================================================
# critic
# ============================================================
bin_size: ???
num_bins: 101
vmin: -5
vmax: 80
rho: 0.5

# ============================================================
# architecture
# ============================================================
latent_dim: 512
model_size: ???
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 512
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8

# ============================================================
# environment
# ============================================================
task: cruise
episodic: true








# ============================================================
# planning
# ============================================================
mpc: true

# MPPI迭代次数
iterations: 6

num_samples: 512
num_elites: 64
num_pi_trajs: 24

min_std: 0.05
max_std: 2
temperature: 1.0

# ============================================================
# actor
# ============================================================
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-3



# ============================================================
# logging
# ============================================================
wandb_project: ???
wandb_entity: ???
wandb_silent: false
enable_wandb: true
save_csv: true

# ============================================================
# misc
# ============================================================
compile: false
save_video: false
save_agent: true
seed: 1

# ============================================================
# convenience
# ============================================================
work_dir: ???
task_title: ???
tasks: ???

action_dim: 2 # 动作维度: 方向盘 [-1, 1], 目标加速度踏板 [-1, 1]


